### ISSUE TITLE
expose Github Actions CI artefacts

### ISSUE THREAD

**Issue by Nelson-numerical-software** [PortAudio/portaudio#558]
It could be great (specially for Windows platforms) to export Github actions artefacts. (.dll, .lib, .h)

```
 - uses: actions/upload-artifact@v1
      with:
        name: github-action-artifacts
        path: artifacts/
```
